// GENERATED by api-automation-factory — DO NOT EDIT
// Owned path: regenerated on propose. Hand edits belong in support/fixtures.
import { z } from "zod";

export const deleteOrderResponseSchema = z.record(z.string(), z.unknown());
