// GENERATED by api-automation-factory — DO NOT EDIT
// Owned path: regenerated on propose. Hand edits belong in support/fixtures.
import { test, expect } from "@playwright/test";
import { getOrderByIdResponseSchema } from "../schemas/getOrderById.schema.js";
import { loadAuthHeaders } from "../../../support/fixtures/auth.js";
import { expectZod } from "../../../support/fixtures/expectZod.js";

test.describe("demo http getOrderById", () => {
  test("GET /orders/{orderId}", async ({ request }) => {
    const headers = loadAuthHeaders("demo");
    const path = "/orders/demo-1";
    const response = await request.fetch(path, {
      method: "GET",
      headers,
      data: undefined,
    });
    expect(response.ok(), `status ${response.status()}`).toBeTruthy();
    const body: unknown = await response.json();
    expectZod(getOrderByIdResponseSchema, body);
  });
});
