import { mkdirSync, writeFileSync, rmSync, existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import type { CoverageIr, Capability } from "../inventory/ir.js";
import { assertSupportedIrVersion } from "../inventory/ir.js";

const BANNER = `// GENERATED by api-automation-factory — DO NOT EDIT
// Owned path: regenerated on propose. Hand edits belong in support/fixtures.
`;

const SECRET_PATTERN =
  /(Authorization\s*:\s*\S+)|(\bBearer\s+[A-Za-z0-9\-._~+/]+=*)|(\bsk-[A-Za-z0-9]{10,})/i;

export function assertNoSecretsInGenerated(content: string, filePath: string): void {
  if (SECRET_PATTERN.test(content)) {
    throw Object.assign(
      new Error(`secret-like material in generated file: ${filePath}`),
      { failureClass: "setup" as const },
    );
  }
}

function isRolloutExcluded(cap: Capability, ir: CoverageIr): boolean {
  return ir.intentionallyUncovered.some(
    (u) =>
      u.toolName === cap.toolName && u.reason !== "mutation-not-allowlisted",
  );
}

function shouldEmitLiveMcp(cap: Capability, ir: CoverageIr): boolean {
  // Mutation fail-closed: non-allowlisted mutators are not invoked live (AE7).
  // Rollout exclusions still receive MCP-floor propose coverage (KD7 / demo DoD).
  return !ir.intentionallyUncovered.some(
    (u) =>
      u.toolName === cap.toolName && u.reason === "mutation-not-allowlisted",
  );
}

export function emitHttpSuites(ir: CoverageIr, outDir: string): string[] {
  assertSupportedIrVersion(ir.version);
  if (existsSync(outDir)) rmSync(outDir, { recursive: true, force: true });
  mkdirSync(outDir, { recursive: true });

  const written: string[] = [];
  for (const cap of ir.capabilities.filter(
    (c) => c.httpMapped && !isRolloutExcluded(c, ir),
  )) {
    const file = join(outDir, `${cap.toolName}.generated.spec.ts`);
    const content = `${BANNER}import { test, expect } from "@playwright/test";
import { ${cap.toolName}ResponseSchema } from "../schemas/${cap.toolName}.schema.js";
import { loadAuthHeaders } from "../../../support/fixtures/auth.js";
import { expectZod } from "../../../support/fixtures/expectZod.js";

test.describe(${JSON.stringify(ir.serviceId + " http " + cap.toolName)}, () => {
  test(${JSON.stringify(cap.method + " " + (cap.path ?? ""))}, async ({ request }) => {
    const headers = loadAuthHeaders(${JSON.stringify(ir.serviceId)});
    const path = ${JSON.stringify((cap.path ?? "/").replace(/\{[^}]+\}/g, "demo-1"))};
    const response = await request.fetch(path, {
      method: ${JSON.stringify(cap.method ?? "GET")},
      headers,
    });
    expect(response.ok(), \`status \${response.status()}\`).toBeTruthy();
    const body: unknown = await response.json();
    expectZod(${cap.toolName}ResponseSchema, body);
  });
});
`;
    assertNoSecretsInGenerated(content, file);
    writeFileSync(file, content, "utf8");
    written.push(file);
  }
  return written.sort();
}

export function emitMcpSuites(ir: CoverageIr, outDir: string): string[] {
  assertSupportedIrVersion(ir.version);
  if (existsSync(outDir)) rmSync(outDir, { recursive: true, force: true });
  mkdirSync(outDir, { recursive: true });

  const written: string[] = [];
  for (const cap of ir.capabilities) {
    if (!shouldEmitLiveMcp(cap, ir)) continue;
    const file = join(outDir, `${cap.toolName}.generated.spec.ts`);
    const content = `${BANNER}import { test, expect } from "@playwright/test";
import { ${cap.toolName}ResponseSchema } from "../schemas/${cap.toolName}.schema.js";
import { callDemoMcpTool } from "../../../support/fixtures/mcpClient.js";
import { expectZod } from "../../../support/fixtures/expectZod.js";

test.describe(${JSON.stringify(ir.serviceId + " mcp " + cap.toolName)}, () => {
  test(${JSON.stringify("callTool " + cap.toolName)}, async () => {
    const result = await callDemoMcpTool(${JSON.stringify(cap.toolName)}, {});
    expect(result.isError, "MCP tool returned isError").toBeFalsy();
    const payload = result.structuredContent ?? result.content;
    expectZod(${cap.toolName}ResponseSchema, payload);
  });
});
`;
    assertNoSecretsInGenerated(content, file);
    writeFileSync(file, content, "utf8");
    written.push(file);
  }
  return written.sort();
}
