import { mkdirSync, writeFileSync, rmSync, existsSync, readdirSync, unlinkSync } from "node:fs";
import { join } from "node:path";
import type { CoverageIr, Capability } from "../inventory/ir.js";
import { assertSupportedIrVersion } from "../inventory/ir.js";

const BANNER = `// GENERATED by api-automation-factory — DO NOT EDIT
// Owned path: regenerated on propose. Hand edits belong in support/fixtures.
`;

const SECRET_PATTERN =
  /(Authorization\s*:\s*\S+)|(\bBearer\s+[A-Za-z0-9\-._~+/]+=*)|(\bsk-[A-Za-z0-9]{10,})/i;

export type SuiteEmitOptions = {
  /** Import prefix used for auth/expectZod/mcpClient helpers (no trailing slash). */
  supportImportBase?: string;
};

const DEFAULT_SUPPORT_IMPORT = "../../../support/fixtures";

export function assertNoSecretsInGenerated(content: string, filePath: string): void {
  if (SECRET_PATTERN.test(content)) {
    throw Object.assign(
      new Error(`secret-like material in generated file: ${filePath}`),
      { failureClass: "setup" as const },
    );
  }
}

function isRolloutExcluded(cap: Capability, ir: CoverageIr): boolean {
  return ir.intentionallyUncovered.some(
    (u) =>
      u.toolName === cap.toolName && u.reason !== "mutation-not-allowlisted",
  );
}

function shouldEmitLiveMcp(cap: Capability, ir: CoverageIr): boolean {
  return !ir.intentionallyUncovered.some(
    (u) =>
      u.toolName === cap.toolName && u.reason === "mutation-not-allowlisted",
  );
}

/** Sample path for generated HTTP tests — prefer numeric ids for public APIs. */
export function samplePath(serviceId: string, pathTemplate: string): string {
  const sample = serviceId === "demo" ? "demo-1" : "1";
  return pathTemplate.replace(/\{[^}]+\}/g, sample);
}

/** Sample MCP args from capability input schema (path/query/body props). */
export function sampleMcpArgs(cap: Capability, serviceId: string): Record<string, unknown> {
  const schema = cap.inputSchema as
    | { properties?: Record<string, { type?: string }>; required?: string[] }
    | undefined;
  const idSample = serviceId === "demo" ? "demo-1" : 1;
  if (!schema?.properties) {
    if (cap.path?.includes("{")) return { id: idSample, orderId: idSample };
    return {};
  }
  const args: Record<string, unknown> = {};
  const required = new Set(
    schema.required && schema.required.length > 0
      ? schema.required
      : Object.keys(schema.properties),
  );
  for (const key of required) {
    const prop = schema.properties[key];
    if (!prop) continue;
    if (prop.type === "integer" || prop.type === "number") args[key] = 1;
    else if (prop.type === "boolean") args[key] = true;
    else if (key === "title") args[key] = "factory-spike-title";
    else if (key === "body") args[key] = "factory-spike-body";
    else if (key === "orderId" || key === "id") args[key] = idSample;
    else args[key] = String(idSample);
  }
  return args;
}

function clearMatching(outDir: string, suffix: string): void {
  if (!existsSync(outDir)) return;
  for (const name of readdirSync(outDir)) {
    if (name.endsWith(suffix)) unlinkSync(join(outDir, name));
  }
}

export function emitHttpSuites(
  ir: CoverageIr,
  outDir: string,
  opts: SuiteEmitOptions = {},
): string[] {
  assertSupportedIrVersion(ir.version);
  mkdirSync(outDir, { recursive: true });
  clearMatching(outDir, ".http.spec.ts");

  const support = opts.supportImportBase ?? DEFAULT_SUPPORT_IMPORT;
  const written: string[] = [];
  for (const cap of ir.capabilities.filter(
    (c) => c.httpMapped && !isRolloutExcluded(c, ir),
  )) {
    const file = join(outDir, `${cap.toolName}.http.spec.ts`);
    const method = cap.method ?? "GET";
    const needsBody = method === "POST" || method === "PUT" || method === "PATCH";
    const bodyLiteral = needsBody
      ? JSON.stringify({ title: "factory-spike-title", body: "factory-spike-body", userId: 1 })
      : "undefined";
    const content = `${BANNER}import { test, expect } from "@playwright/test";
import { ${cap.toolName}ResponseSchema } from "../schemas/${cap.toolName}.schema.js";
import { loadAuthHeaders } from "${support}/auth.js";
import { expectZod } from "${support}/expectZod.js";

test.describe(${JSON.stringify(ir.serviceId + " http " + cap.toolName)}, () => {
  test(${JSON.stringify(method + " " + (cap.path ?? ""))}, async ({ request }) => {
    const headers = loadAuthHeaders(${JSON.stringify(ir.serviceId)});
    const path = ${JSON.stringify(samplePath(ir.serviceId, cap.path ?? "/"))};
    const response = await request.fetch(path, {
      method: ${JSON.stringify(method)},
      headers,
      data: ${bodyLiteral},
    });
    expect(response.ok(), \`status \${response.status()}\`).toBeTruthy();
    const body: unknown = await response.json();
    expectZod(${cap.toolName}ResponseSchema, body);
  });
});
`;
    assertNoSecretsInGenerated(content, file);
    writeFileSync(file, content, "utf8");
    written.push(file);
  }
  return written.sort();
}

export function emitMcpSuites(
  ir: CoverageIr,
  outDir: string,
  opts: SuiteEmitOptions = {},
): string[] {
  assertSupportedIrVersion(ir.version);
  mkdirSync(outDir, { recursive: true });
  clearMatching(outDir, ".mcp.spec.ts");

  const support = opts.supportImportBase ?? DEFAULT_SUPPORT_IMPORT;
  const written: string[] = [];
  for (const cap of ir.capabilities) {
    if (!shouldEmitLiveMcp(cap, ir)) continue;
    const file = join(outDir, `${cap.toolName}.mcp.spec.ts`);
    const args = sampleMcpArgs(cap, ir.serviceId);
    const content = `${BANNER}import { test, expect } from "@playwright/test";
import { ${cap.toolName}ResponseSchema } from "../schemas/${cap.toolName}.schema.js";
import { callMcpTool } from "${support}/mcpClient.js";
import { expectZod } from "${support}/expectZod.js";

test.describe(${JSON.stringify(ir.serviceId + " mcp " + cap.toolName)}, () => {
  test(${JSON.stringify("callTool " + cap.toolName)}, async () => {
    const result = await callMcpTool(${JSON.stringify(ir.serviceId)}, ${JSON.stringify(cap.toolName)}, ${JSON.stringify(args)});
    expect(result.isError, "MCP tool returned isError").toBeFalsy();
    const payload = result.structuredContent ?? result.content;
    expectZod(${cap.toolName}ResponseSchema, payload);
  });
});
`;
    assertNoSecretsInGenerated(content, file);
    writeFileSync(file, content, "utf8");
    written.push(file);
  }
  return written.sort();
}

/** Clear a service emit root before rewriting (fixture or workspace landing). */
export function resetEmitRoot(baseDir: string): void {
  if (existsSync(baseDir)) rmSync(baseDir, { recursive: true, force: true });
  mkdirSync(baseDir, { recursive: true });
}
