import { mkdirSync, writeFileSync, existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { assertNoSecretsInGenerated } from "./http.js";

/** Marker present in every overwrite-owned kit file. */
export const SUPPORT_KIT_OWNED_MARKER =
  "GENERATED by api-automation-factory — DO NOT EDIT";

const BANNER = `// ${SUPPORT_KIT_OWNED_MARKER}
// Owned path: regenerated on propose. Hand-owned overrides: omit this banner or use a different filename.
`;

export const SUPPORT_KIT_FILES = ["auth.ts", "expectZod.ts", "mcpClient.ts"] as const;
export type SupportKitFile = (typeof SUPPORT_KIT_FILES)[number];

/**
 * Workspace-ready kit sources. Export names must match emit imports:
 * loadAuthHeaders, expectZod, callMcpTool.
 */
const KIT_SOURCES: Record<SupportKitFile, string> = {
  "auth.ts": `import { existsSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import YAML from "yaml";

export class AuthError extends Error {
  readonly failureClass = "auth" as const;
  constructor(message: string) {
    super(message);
    this.name = "AuthError";
  }
}

type AuthProfile = {
  id: string;
  type: "none" | "api_key" | "bearer" | "basic";
  headerName?: string;
  env: {
    token?: string;
    username?: string;
    password?: string;
  };
};

const ENV_NAME = /^[A-Z0-9_]+$/;
const VALUE_LIKE = /^(Bearer\\s+|sk-|ghp_|xox[baprs]-)/i;

function loadProfile(profilePath: string): AuthProfile {
  if (!existsSync(profilePath)) {
    throw new AuthError(\`auth profile not found: \${profilePath}\`);
  }
  const raw = YAML.parse(readFileSync(profilePath, "utf8")) as {
    id?: string;
    type?: AuthProfile["type"];
    headerName?: string;
    env?: Record<string, string>;
  };
  for (const [k, v] of Object.entries(raw.env ?? {})) {
    if (typeof v === "string" && (!ENV_NAME.test(v) || VALUE_LIKE.test(v))) {
      throw new AuthError(\`auth profile must use env var names only (bad \${k})\`);
    }
  }
  if (!raw.id || !raw.type) {
    throw new AuthError("auth profile missing id/type");
  }
  return {
    id: raw.id,
    type: raw.type,
    headerName: raw.headerName,
    env: raw.env ?? {},
  };
}

function headersFromProfile(
  profile: AuthProfile,
  env: NodeJS.ProcessEnv = process.env,
): Record<string, string> {
  if (profile.type === "none") return {};
  if (profile.type === "api_key" || profile.type === "bearer") {
    const name = profile.env.token;
    if (!name) throw new AuthError("profile missing env.token");
    const value = env[name];
    if (!value) throw new AuthError(\`missing required secret env: \${name}\`);
    const header = profile.headerName ?? "Authorization";
    const headerValue =
      profile.type === "bearer" || header.toLowerCase() === "authorization"
        ? \`Bearer \${value}\`
        : value;
    return { [header]: headerValue };
  }
  if (profile.type === "basic") {
    const u = profile.env.username;
    const p = profile.env.password;
    if (!u || !p) throw new AuthError("basic profile requires env.username and env.password");
    const user = env[u];
    const pass = env[p];
    if (!user || !pass) throw new AuthError("missing basic auth secrets");
    const token = Buffer.from(\`\${user}:\${pass}\`).toString("base64");
    return { ["Authorization"]: \`Basic \${token}\` };
  }
  throw new AuthError(\`unsupported auth type: \${profile.type}\`);
}

/**
 * Runtime auth header loader for workspace suites.
 * Profiles live next to the kit: playwright/api/support/profiles/<serviceId>.yaml
 * (env names only — never resolved secret values).
 */
export function loadAuthHeaders(serviceId: string): Record<string, string> {
  const supportRoot = dirname(fileURLToPath(import.meta.url));
  const profilePath = join(supportRoot, "profiles", \`\${serviceId}.yaml\`);
  try {
    return headersFromProfile(loadProfile(profilePath));
  } catch (err) {
    if (err instanceof AuthError) {
      throw Object.assign(new Error(\`auth: \${err.message}\`), {
        failureClass: "auth" as const,
        name: "AuthError",
      });
    }
    throw err;
  }
}
`,

  "expectZod.ts": `import { expect } from "@playwright/test";
import type { z } from "zod";

export type FailureClass = "contract" | "auth" | "transport" | "setup";

export function expectZod(schema: z.ZodType, body: unknown): void {
  const result = schema.safeParse(body);
  if (!result.success) {
    const err = Object.assign(
      new Error(\`contract: zod validation failed: \${result.error.message}\`),
      { failureClass: "contract" as FailureClass },
    );
    expect(result.success, err.message).toBe(true);
  }
}
`,

  "mcpClient.ts": `/**
 * Workspace MCP client — calls a service MCP HTTP endpoint.
 * Configure with MCP_BASE_URL_<SERVICEID> or MCP_BASE_URL (uppercase service id).
 */
export type McpCallResult = {
  isError: boolean;
  structuredContent?: unknown;
  content?: unknown;
};

function mcpBaseUrl(serviceId: string): string {
  const specific = process.env[\`MCP_BASE_URL_\${serviceId.toUpperCase().replace(/[^A-Z0-9]/g, "_")}\`];
  const fallback = process.env.MCP_BASE_URL;
  const url = specific ?? fallback;
  if (!url) {
    throw Object.assign(
      new Error(
        \`setup: set MCP_BASE_URL_\${serviceId.toUpperCase()} or MCP_BASE_URL for live MCP calls\`,
      ),
      { failureClass: "setup" as const },
    );
  }
  return url.replace(/\\/$/, "");
}

export async function callMcpTool(
  serviceId: string,
  name: string,
  args: Record<string, unknown> = {},
): Promise<McpCallResult> {
  const base = mcpBaseUrl(serviceId);
  let response: Response;
  try {
    response = await fetch(\`\${base}/mcp\`, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ name, arguments: args }),
    });
  } catch (err) {
    throw Object.assign(
      new Error(
        \`transport: MCP unreachable at \${base}/mcp: \${err instanceof Error ? err.message : String(err)}\`,
      ),
      { failureClass: "transport" as const },
    );
  }
  if (!response.ok) {
    throw Object.assign(new Error(\`transport: MCP HTTP \${response.status}\`), {
      failureClass: "transport" as const,
    });
  }
  return (await response.json()) as McpCallResult;
}
`,
};

export type EmitSupportKitResult = {
  written: string[];
  skippedHandOwned: string[];
  supportRoot: string;
};

/**
 * Emit overwrite-owned support kit into playwright/api/support/ (or equivalent).
 * Preserves adjacent hand-owned files and same-named files that lack the owned marker.
 */
export function emitSupportKit(supportRoot: string): EmitSupportKitResult {
  mkdirSync(supportRoot, { recursive: true });
  const written: string[] = [];
  const skippedHandOwned: string[] = [];

  for (const name of SUPPORT_KIT_FILES) {
    const dest = join(supportRoot, name);
    if (existsSync(dest)) {
      const existing = readFileSync(dest, "utf8");
      if (!existing.includes(SUPPORT_KIT_OWNED_MARKER)) {
        skippedHandOwned.push(dest);
        continue;
      }
    }
    const content = `${BANNER}${KIT_SOURCES[name]}`;
    assertNoSecretsInGenerated(content, dest);
    writeFileSync(dest, content, "utf8");
    written.push(dest);
  }

  return { written, skippedHandOwned, supportRoot };
}
