import { mkdirSync, writeFileSync, rmSync, existsSync } from "node:fs";
import { join } from "node:path";
import {
  assertSupportedIrVersion,
  type CoverageIr,
  type Capability,
} from "../inventory/ir.js";

const BANNER = `// GENERATED by api-automation-factory — DO NOT EDIT
// Owned path: regenerated on propose. Hand edits belong in support/fixtures.
`;

function jsonSchemaToZod(schema: unknown, name: string): string {
  if (!schema || typeof schema !== "object") {
    return `export const ${name} = z.unknown();`;
  }
  const s = schema as {
    type?: string;
    properties?: Record<string, unknown>;
    required?: string[];
    enum?: unknown[];
    items?: unknown;
  };

  if (s.enum && Array.isArray(s.enum)) {
    const vals = s.enum.map((v) => JSON.stringify(v)).join(", ");
    return `export const ${name} = z.enum([${vals}] as const);`;
  }

  if (s.type === "object" && s.properties) {
    const required = new Set(s.required ?? []);
    const fields = Object.entries(s.properties)
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([key, prop]) => {
        const inner = inlineZod(prop);
        const optional = required.has(key) ? "" : ".optional()";
        return `  ${JSON.stringify(key)}: ${inner}${optional},`;
      })
      .join("\n");
    return `export const ${name} = z.object({\n${fields}\n});`;
  }

  if (s.type === "array") {
    return `export const ${name} = z.array(${inlineZod(s.items)});`;
  }

  return `export const ${name} = ${inlineZod(schema)};`;
}

function inlineZod(schema: unknown): string {
  if (!schema || typeof schema !== "object") return "z.unknown()";
  const s = schema as {
    type?: string;
    enum?: unknown[];
    properties?: Record<string, unknown>;
    required?: string[];
    items?: unknown;
  };
  if (s.enum) {
    return `z.enum([${s.enum.map((v) => JSON.stringify(v)).join(", ")}] as const)`;
  }
  switch (s.type) {
    case "string":
      return "z.string()";
    case "integer":
    case "number":
      return "z.number()";
    case "boolean":
      return "z.boolean()";
    case "array":
      return `z.array(${inlineZod(s.items)})`;
    case "object": {
      if (!s.properties) return "z.record(z.string(), z.unknown())";
      const required = new Set(s.required ?? []);
      const fields = Object.entries(s.properties)
        .sort(([a], [b]) => a.localeCompare(b))
        .map(([key, prop]) => {
          const optional = required.has(key) ? "" : ".optional()";
          return `${JSON.stringify(key)}: ${inlineZod(prop)}${optional}`;
        })
        .join(", ");
      return `z.object({ ${fields} })`;
    }
    default:
      return "z.unknown()";
  }
}

function schemaForCapability(cap: Capability): unknown {
  if (cap.openApiResponseSchema) return cap.openApiResponseSchema;
  if (cap.outputSchema) return cap.outputSchema;
  return { type: "object" };
}

export function emitZodSchemas(ir: CoverageIr, outDir: string): string[] {
  assertSupportedIrVersion(ir.version);
  if (existsSync(outDir)) {
    rmSync(outDir, { recursive: true, force: true });
  }
  mkdirSync(outDir, { recursive: true });

  const written: string[] = [];
  const indexExports: string[] = [];

  for (const cap of [...ir.capabilities].sort((a, b) => a.id.localeCompare(b.id))) {
    const exportName = `${cap.toolName}ResponseSchema`;
    const fileBase = `${cap.toolName}.schema.ts`;
    const body = `${BANNER}import { z } from "zod";\n\n${jsonSchemaToZod(schemaForCapability(cap), exportName)}\n`;
    const filePath = join(outDir, fileBase);
    writeFileSync(filePath, body, "utf8");
    written.push(filePath);
    indexExports.push(
      `export { ${exportName} } from "./${cap.toolName}.schema.js";`,
    );
  }

  const indexPath = join(outDir, "index.ts");
  writeFileSync(
    indexPath,
    `${BANNER}${indexExports.sort().join("\n")}\n`,
    "utf8",
  );
  written.push(indexPath);
  return written.sort();
}
